### ISSUE TITLE
为什么我这么优秀？

### ISSUE THREAD

**Issue by xieyinpeng** [ShortPupil/ShortPupil.github.io#8]
在我翻开这一个个项目时，我时常会想着：为什么我这个人如此的优秀？
所以，今天我用小号在这里提出了问题，希望有一天能够有所回答。
•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•́✧•̀.̫•
( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)( ･ิω･ิ)

**Comment by ShortPupil** [comment]
你是不是憨憨
